go

diff --git a/.github/workflows/called-bulk.yml b/.github/workflows/called-bulk.yml
--- a/.github/workflows/called-bulk.yml
+++ b/.github/workflows/called-bulk.yml
@@ -6,10 +6,20 @@ on:
       env:
         type: string
         required: true
-      SN:
+      env_name:
         type: string
         required: true
-        
+      bg:
+        type: string
+        required: true
+      size:
+        type: string
+        required: false
+        default: "small"
+      no:
+        type: number
+        required: false
+        default: "1"
 
 jobs:
   reuse-job:
@@ -18,8 +28,11 @@ jobs:
     steps:
       - name: print inputs
         run: |
-          echo "SN: ${{ inputs.SN }}"
+          echo "bg: ${{ inputs.bg }}"
           echo "env: ${{ inputs.env }}"
+          echo "env_name: ${{ inputs.env_name }}"
+          echo "size: ${{ inputs.size }}"
+          echo "no: ${{ inputs.no }}"
 
       - name: checkout
         uses: actions/checkout@v4.1.6
@@ -27,41 +40,40 @@ jobs:
       - name: read config
         id: json
         run: |
-          name=$(jq '.${{inputs.SN}}.name' config.json)
-          echo "name: $name"
-
-          if [[ "${{inputs.env}}" == "dev" ]]
-          then
-
-            echo "dev"
-            env_id=$(jq '.${{inputs.SN}}.DEV' config.json)
-            
+          keys=$(jq -r 'keys[]' config.json)
+          for key in $keys; do
+            echo "Key: $key"
           
-          elif [[ "${{inputs.env}}" == "prod" ]]
-          then
+            bg=$key
+            echo "bg=$bg" >> $GITHUB_OUTPUT
+            bg_lower=$(echo $bg | tr 'A-Z' 'a-z')
+            echo "bg_lower=$bg_lower" >> $GITHUB_OUTPUT
 
-            echo "prod"
-            env_id=$(jq '.${{inputs.SN}}.PROD' config.json)
-            
+            env=$(echo ${{inputs.env}} | tr 'A-Z' 'a-z')
+            if [[ "env" == "dev" ]]; then
+              env_id=$(jq '.$key.DEV' config.json)
+            elif [[ "${{inputs.env}}" == "prod" ]]; then
+              env_id=$(jq '.$key.PROD' config.json)
+            elif [[ "$key" == "qa" ]]; then
+              env_id=$(jq '.$key.QA' config.json)
+            else
+              echo "Invalid env"
+              exit 1
+            fi
 
-          elif [[ "${{inputs.env}}" == "qa" ]]
-          then
-
-            echo "qa"
-            env_id=$(jq '.${{inputs.SN}}.QA' config.json)
-            
-
-          else
-            echo "Invalid env"
-            exit 1
-          fi
+          done
 
           echo "env_id: $env_id"
           echo "env_id=$env_id" >> $GITHUB_OUTPUT
 
       - name: display
         run: |
+ 
+          echo "bg: ${{steps.json.outputs.bg}}"
+          echo "bg_lower: ${{steps.json.outputs.bg_lower}}"
+          echo "env_name: ${{steps.json.outputs.env_name}}"
           echo "env_id: ${{steps.json.outputs.env_id}}"
+
           
           
 
